version: '3'

volumes:
  sessions:

networks:
  play-with-docker:
    driver: bridge

services:
  play-with-docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: dimaskiddo/play-with-docker:latest
    container_name: 'play-with-docker'
    healthcheck:
      disable: true
    command:
      - play-with-docker
      - -name
      - play-with-docker
      - -l2
      - play-with-docker-router
      - -save
      - /usr/app/play-with-docker/sessions/session
    networks:
      - play-with-docker
    ports:
      - "80:3000"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - sessions:/usr/app/play-with-docker/sessions

  play-with-docker-router:
    build:
      context: .
      dockerfile: Dockerfile.l2
    image: dimaskiddo/play-with-docker:l2
    container_name: 'play-with-docker-router'
    healthcheck:
      disable: true
    command:
      - play-with-docker-l2
      - -name
      - play-with-docker
      - -l2
      - play-with-docker-router
      - -save
      - /usr/app/play-with-docker/sessions/networks
      - -ssh-key-path
      - /etc/ssh/ssh_host_rsa_key
    networks:
      - play-with-docker
    ports:
      - "8022:22"
      - "8053:53"
      - "443:443"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - sessions:/usr/app/play-with-docker/sessions
