version: '3'

volumes:
  data:
  certs:
  sessions:

networks:
  play-with-docker:
    driver: bridge

services:
  play-with-docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: dimaskiddo/play-with-docker:latest
    container_name: 'play-with-docker'
    healthcheck:
      disable: true
    security_opt:
      - apparmor:unconfined
    networks:
      - play-with-docker
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/usr/app/play-with-docker/data
      - certs:/usr/app/play-with-docker/certs
      - sessions:/usr/app/play-with-docker/sessions

  play-with-docker-router:
    build:
      context: .
      dockerfile: Dockerfile.l2
    image: dimaskiddo/play-with-docker:l2
    container_name: 'play-with-docker-router'
    healthcheck:
      disable: true
    security_opt:
      - apparmor:unconfined
    networks:
      - play-with-docker
    ports:
      - "2222:22"
      - "5353:53"
      - "443:443"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/usr/app/play-with-docker/data
      - certs:/usr/app/play-with-docker/certs
      - sessions:/usr/app/play-with-docker/sessions
