global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

rule_files:
scrape_configs:
  - job_name: ''play-with-docker'
    static_configs:
      - targets: ['play-with-docker:3000']
